Repository djLeeeee/project1, pull requests merged in 2022-04, with the labels that each got.

#18 4월 13일 프로젝트 진행
  .gitignore
  meeting/settings.py
  plans/migrations/0002_plan_created_at.py
  plans/models.py
  plans/templates/plans/index.html
  plans/views.py
Labels: bug, enhancement

#24 plan admin 추가 / admin 페이지에서 계획 생성 가능
  plans/admin.py
Labels: enhancement

#25 plan_date에 해당 날짜 모든 약속 조회 기능 추가
  plans/templates/plans/index.html
  plans/templates/plans/plan_date.html
  plans/urls.py
  plans/views.py
Labels: enhancement

#26 Modify plan_update.html
  plans/templates/plans/plan_update.html
Labels: enhancement

#33 로그인, 로그아웃 추가
  accounts/templates/accounts/login.html
  accounts/urls.py
  accounts/views.py
  plans/views.py
  templates/base.html
Labels: bug, enhancement

#35 자잘한 기능 수정
  plans/templates/plans/plan_detail.html
  plans/views.py
  static/base.css
  templates/base.html
Labels: enhancement

#40 accounts/models.py User 정보 수정
  accounts/migrations/0002_auto_20220418_0011.py
  accounts/models.py
Labels: bug

#50 base.html 수정 + 댓글 collapse
  plans/templates/plans/plan_detail.html
  static/base.css
  templates/base.html
Labels: enhancement

#52 detail 페이지 수정
  plans/templates/plans/plan_detail.html
Labels: enhancement

#57 약속 있는 날짜 조회/신규 약속 표시 로직 변경
  plans/templates/plans/index.html
  plans/views.py
Labels: enhancement

#58 버튼 박스 위치 조정
  plans/templates/plans/plan_detail.html
Labels: enhancement

#59 plan_delete, my_page 포맷 생성
  accounts/templates/accounts/my_page.html
  accounts/urls.py
  accounts/views.py
  plans/templates/plans/plan_detail.html
  plans/urls.py
  plans/views.py
  templates/base.html
Labels: enhancement

#68 detail 페이지 수정
  plans/templates/plans/plan_detail.html
Labels: enhancement

#73 뒤로 가기 버튼 수정
  accounts/templates/accounts/login.html
  accounts/templates/accounts/my_page.html
  accounts/templates/accounts/signup.html
  plans/templates/plans/index.html
  plans/templates/plans/plan_coming.html
  plans/templates/plans/plan_create.html
  plans/templates/plans/plan_date.html
  plans/templates/plans/plan_detail.html
  plans/templates/plans/plan_update.html
  static/base.css
  templates/base.html
Labels: enhancement
